version: "3"

services:
  spring-petclinic:
    depends_on: 
      - mysql
    image: wahab99/petclinic:latest
    restart: always
    ports:
      - "8088:8080"
    environment:
      - MYSQL_HOST= mysql


  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
